# Server
server.port=8080

# SendGrid
sendgrid.api.key=${SENDGRID_API_KEY}
app.sender.email=${SPRING_MAIL_USERNAME:hyyadav48485@gmail.com}

# Resume
app.resume.path=resume/Himanshu_Yadav_Latest_Resume.pdf
app.resume.filename=Himanshu_Yadav_Latest_Resume.pdf

# CORS
app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:http://localhost:5173}

# Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB